grafana:
  enabled: true
  sidecar: 
    datasources: 
      enabled: true 
  resources:
    requests:
      memory: ${resources_requests_memory}
      cpu: ${resources_requests_cpu}
    limits:
      memory: ${resources_limits_memory}
      cpu: ${resources_limits_cpu}
  adminUser: admin
  admin:
    existingSecret: grafana-auth
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
      database:
        type: ${db_type}
        ssl_mode: ${db_ssl_mode}
        host: ${db_host}
        name: ${db_name}
        user: ${db_user}
        password: ${db_password}
