apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${clusterissuer_name}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${email_address}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${clusterissuer_name}-secret
    # Add a single challenge solver, HTTP01 using nginx
    solvers: ${solvers}
