apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${clusterissuer_name}
spec:
  acme:
    email: ${email_address}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${clusterissuer_name}-secret
    solvers:
    - dns01:
        cloudDNS:
          project: ${project}
          serviceAccountSecretRef:
            name: ${secretaccesskeysecretref_name}
            key: ${secretaccesskeysecretref_key}